# if dont want to mess with your os env
version: '3.1'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.local
    restart: always
    depends_on:
      - db
    environment:
      db_name: todo
      db_username: iiidevops
      db_password: templatePassword
      db_host: db
    ports:
      - 8080
  db:
    mongodb:
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    restart: always
    ports:
      - "27017"
    environment: 
      MONGODB_USERNAME: iiidevops
      MONGODB_PASSWORD: templatePassword
      MONGODB_DATABASE: todo
      MONGODB_ROOT_PASSWORD: templatePassword
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    volumes:
      - ./db:/docker-entrypoint-initdb.d:rw

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - db
    environment: 
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'false'
      ME_CONFIG_MONGODB_AUTH_DATABASE: todo
      ME_CONFIG_MONGODB_AUTH_USERNAME: iiidevops
      ME_CONFIG_MONGODB_AUTH_PASSWORD: templatePassword
    ports:
      - 8081

volumes:
  mongodb_data:
    driver: local